### ISSUE TITLE
Data Set Configuration Error: Unknown Error

### ISSUE THREAD

**Issue by RandomToolGuy** [Gladior-B-V/instagram-insights-connector#8] opened 2023-10-18 05:44 UTC
These errors are appearing on my Instagram Connector in multiple different places. The error message is the same for all of these places. I have tried refreshing the data but to no success. 

**ERROR MESSAGE**
Community Connector Error
There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

Connector details
Unknown Error - There was an error communicating with the service.

**Comment by zoedufrenne** [comment] 2023-10-18 14:35
hi @RandomToolGuy, can you try to make a new connection in the Data Hub with your credentials? (even if it's already there). 
https://datahubapp.gladior.com/workspace 

Sometimes you need to make a new connection, when you've reconnected the credentials, then open the dashboard and refresh the data. Please let me know if it worked!

**Comment by Lgerada** [comment] 2023-10-19 21:19
I'm having the same issues with my connectors. Instagram is showing: :

"Data Set Configuration Error
Looker Studio cannot connect to your data set."

"There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

Connector details
Unknown Error - There was an error communicating with the service.

Error ID: b9b498e0"


When I try to reconnect it and a lot of my attached Instagram connectors are missing.

**Comment by Stefan-Adam** [comment] 2023-11-04 22:55
I am also experiencing issues with the Instagram connector. My Data Studio reports are showing:

"Data Set Configuration Error
Looker Studio cannot connect to your data set."

"Community Connector Error
There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

Connector details
Unknown Error - There was an error communicating with the service.

Error ID: b524eedd"

I have attempted to reconnect the Instagram account several times, both completely removing it in the Data Hub Workspace, and in the report itself, but it has not resolved the issue.

It only seems to be affecting some specific metrics like "Like Count", "Media Reach", whereas others work fine like "Followers", "Follows", "Media Count", and "Impressions"

**Comment by RandomToolGuy** [comment] 2023-11-05 14:51
Any update on this issue yet?

**Comment by m-karakus** [comment] 2023-11-11 23:07
Having the same issue. Any Update on this, please?  

![image](https://i.imgur.com/5f8q0oH.png)

**Comment by jedrysik** [comment] 2023-11-13 13:06
I have the same problem. 
It does work in some metrics and cases (mainly in the default dashboard created by Gladior, but stops when I change the date), but not in the dashboard I created.
I look forward to any updates

**Comment by zoedufrenne** [comment] 2023-11-16 10:09
Hi everyone, thanks for letting us know! We are going to update the Instagram connector. I keep you posted when it's done!

**Comment by zoedufrenne** [comment] 2024-02-09 08:49
HI @jedrysik @m-karakus @RandomToolGuy @Stefan-Adam the connector has granted acces, so the connector should work properly again. Can you all create a new credential to make a new connection to Meta (Instagram). Even if the credentials are already there. With making a new credential you will make a connection to the newest version of the API. Please let me know if it worked!

**Comment by RandomToolGuy** [comment] 2024-02-09 14:30
It seems to be working for me now :)

**Comment by m-karakus** [comment] 2024-02-10 13:51
Yep I can confirm also, thanks!
you can close the issue.

**Comment by zoedufrenne** [comment] 2024-02-12 07:26
That's great to hear! I will close this issue. 
Our support is free, but if you're happy with our support you can always donate through the pink donate button on the right: https://datahubapp.gladior.com/

**Closed as completed by zoedufrenne** 2024-02-12 07:26 UTC
